{% set version = "7.2.0" %}

package:
  name: cx_oracle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Oracle/cx_Oracle-{{ version }}.tar.gz
  sha256: 078f9045fb6ec1e2474ca81356084e4600f0f21b027a08239c345bed8cdebe2c
  patches:
    - 0001-Add-macro-for-isnan-msvc-2008.patch  # [win and vc<14]

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Oracle

about:
  home: https://oracle.github.io/python-cx_Oracle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to Oracle
  doc_url: https://cx-oracle.readthedocs.io/
  dev_url: https://github.com/oracle/python-cx_Oracle

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
